import type { SegmentDef, FieldDef } from './types';

export const SEGMENT_DEFS: Record<string, SegmentDef> = {
  MSH: {
    name: 'MSH',
    description: 'Message Header',
    fields: [
      { position: 1, name: 'Field Separator', dataType: 'ST', required: true, description: 'Separator character' },
      { position: 2, name: 'Encoding Characters', dataType: 'ST', required: true, description: 'Component, repetition, escape, subcomponent delimiters' },
      { position: 3, name: 'Sending Application', dataType: 'HD', required: false, description: 'Application sending the message' },
      { position: 4, name: 'Sending Facility', dataType: 'HD', required: false, description: 'Facility sending the message' },
      { position: 5, name: 'Receiving Application', dataType: 'HD', required: false, description: 'Application receiving the message' },
      { position: 6, name: 'Receiving Facility', dataType: 'HD', required: false, description: 'Facility receiving the message' },
      { position: 7, name: 'Date/Time of Message', dataType: 'TS', required: true, description: 'When the message was created' },
      { position: 8, name: 'Security', dataType: 'ST', required: false, description: 'Security/authorization info' },
      { position: 9, name: 'Message Type', dataType: 'MSG', required: true, description: 'Message type and trigger event' },
      { position: 10, name: 'Message Control ID', dataType: 'ST', required: true, description: 'Unique ID for this message' },
      { position: 11, name: 'Processing ID', dataType: 'PT', required: true, description: 'Processing type (P=Production, T=Training)' },
      { position: 12, name: 'Version ID', dataType: 'VID', required: true, description: 'HL7 version' },
      { position: 13, name: 'Sequence Number', dataType: 'NM', required: false, description: 'Sequence number' },
      { position: 14, name: 'Continuation Pointer', dataType: 'ST', required: false, description: 'Continuation pointer' },
      { position: 15, name: 'Accept Acknowledgment Type', dataType: 'ID', required: false, table: '0155', description: 'Accept ack type' },
      { position: 16, name: 'Application Acknowledgment Type', dataType: 'ID', required: false, table: '0155', description: 'Application ack type' },
      { position: 17, name: 'Country Code', dataType: 'ID', required: false, description: 'Country code' },
      { position: 18, name: 'Character Set', dataType: 'ID', required: false, description: 'Character set' },
      { position: 19, name: 'Principal Language', dataType: 'CE', required: false, description: 'Principal language of message' },
      { position: 20, name: 'Alternate Character Set', dataType: 'ID', required: false, description: 'Alternate character set handling scheme' },
      { position: 21, name: 'Message Profile Identifier', dataType: 'EI', required: false, description: 'Message profile ID' },
    ],
  },
  EVN: {
    name: 'EVN',
    description: 'Event Type',
    fields: [
      { position: 1, name: 'Event Type Code', dataType: 'ID', required: true, description: 'Event type code' },
      { position: 2, name: 'Recorded Date/Time', dataType: 'TS', required: true, description: 'When the event was recorded' },
      { position: 3, name: 'Date/Time Planned Event', dataType: 'TS', required: false, description: 'Planned event date/time' },
      { position: 4, name: 'Event Reason Code', dataType: 'IS', required: false, description: 'Reason for the event' },
      { position: 5, name: 'Operator ID', dataType: 'XCN', required: false, description: 'Operator who triggered the event' },
      { position: 6, name: 'Event Occurred', dataType: 'TS', required: false, description: 'When the event actually occurred' },
    ],
  },
  PID: {
    name: 'PID',
    description: 'Patient Identification',
    fields: [
      { position: 1, name: 'Set ID', dataType: 'SI', required: false, description: 'Sequence identifier' },
      { position: 2, name: 'Patient ID', dataType: 'CX', required: false, description: 'External patient ID' },
      { position: 3, name: 'Patient Identifier List', dataType: 'CX', required: true, description: 'List of patient identifiers' },
      { position: 4, name: 'Alternate Patient ID', dataType: 'CX', required: false, description: 'Alternate patient ID' },
      { position: 5, name: 'Patient Name', dataType: 'XPN', required: true, description: 'Patient name (family, given, middle, suffix, prefix)' },
      { position: 6, name: 'Mother\'s Maiden Name', dataType: 'XPN', required: false, description: "Mother's maiden name" },
      { position: 7, name: 'Date/Time of Birth', dataType: 'TS', required: false, description: 'Patient date of birth' },
      { position: 8, name: 'Administrative Sex', dataType: 'ID', required: false, table: '0001', description: 'Patient sex' },
      { position: 9, name: 'Patient Alias', dataType: 'XPN', required: false, description: 'Patient alias name' },
      { position: 10, name: 'Race', dataType: 'CE', required: false, table: '0005', description: 'Patient race' },
      { position: 11, name: 'Patient Address', dataType: 'XAD', required: false, description: 'Patient address (street, city, state, zip)' },
      { position: 12, name: 'County Code', dataType: 'IS', required: false, description: 'County code' },
      { position: 13, name: 'Phone Number Home', dataType: 'XTN', required: false, description: 'Home phone number' },
      { position: 14, name: 'Phone Number Business', dataType: 'XTN', required: false, description: 'Business phone number' },
      { position: 15, name: 'Primary Language', dataType: 'CE', required: false, description: 'Primary language' },
      { position: 16, name: 'Marital Status', dataType: 'CE', required: false, table: '0002', description: 'Marital status' },
      { position: 17, name: 'Religion', dataType: 'CE', required: false, table: '0006', description: 'Religion' },
      { position: 18, name: 'Patient Account Number', dataType: 'CX', required: false, description: 'Patient account number' },
      { position: 19, name: 'SSN', dataType: 'ST', required: false, description: 'Social Security Number' },
      { position: 20, name: 'Driver\'s License', dataType: 'DLN', required: false, description: "Driver's license number" },
      { position: 21, name: 'Mother\'s Identifier', dataType: 'CX', required: false, description: "Mother's identifier" },
      { position: 22, name: 'Ethnic Group', dataType: 'CE', required: false, table: '0189', description: 'Ethnic group' },
      { position: 23, name: 'Birth Place', dataType: 'ST', required: false, description: 'Birth place' },
      { position: 24, name: 'Multiple Birth Indicator', dataType: 'ID', required: false, description: 'Multiple birth indicator' },
      { position: 25, name: 'Birth Order', dataType: 'NM', required: false, description: 'Birth order' },
      { position: 26, name: 'Citizenship', dataType: 'CE', required: false, description: 'Citizenship' },
      { position: 27, name: 'Veterans Military Status', dataType: 'CE', required: false, description: 'Veterans military status' },
    ],
  },
  PV1: {
    name: 'PV1',
    description: 'Patient Visit',
    fields: [
      { position: 1, name: 'Set ID', dataType: 'SI', required: false, description: 'Sequence identifier' },
      { position: 2, name: 'Patient Class', dataType: 'ID', required: true, table: '0004', description: 'Patient class (I=Inpatient, O=Outpatient, E=Emergency)' },
      { position: 3, name: 'Assigned Patient Location', dataType: 'PL', required: false, description: 'Assigned patient location' },
      { position: 4, name: 'Admission Type', dataType: 'ID', required: false, table: '0007', description: 'Admission type' },
      { position: 5, name: 'Pre-admission Number', dataType: 'CX', required: false, description: 'Pre-admission number' },
      { position: 6, name: 'Prior Patient Location', dataType: 'PL', required: false, description: 'Prior patient location' },
      { position: 7, name: 'Attending Doctor', dataType: 'XCN', required: false, description: 'Attending doctor' },
      { position: 8, name: 'Referring Doctor', dataType: 'XCN', required: false, description: 'Referring doctor' },
      { position: 9, name: 'Consulting Doctor', dataType: 'XCN', required: false, description: 'Consulting doctor' },
      { position: 10, name: 'Hospital Service', dataType: 'IS', required: false, description: 'Hospital service' },
      { position: 11, name: 'Temporary Location', dataType: 'PL', required: false, description: 'Temporary location' },
      { position: 12, name: 'Preadmit Test Indicator', dataType: 'ID', required: false, description: 'Preadmit test indicator' },
      { position: 13, name: 'Re-admission Indicator', dataType: 'ID', required: false, description: 'Re-admission indicator' },
      { position: 14, name: 'Admit Source', dataType: 'IS', required: false, table: '0023', description: 'Admit source' },
      { position: 15, name: 'Ambulatory Status', dataType: 'IS', required: false, description: 'Ambulatory status' },
      { position: 16, name: 'VIP Indicator', dataType: 'ID', required: false, description: 'VIP indicator' },
      { position: 17, name: 'Admitting Doctor', dataType: 'XCN', required: false, description: 'Admitting doctor' },
      { position: 18, name: 'Patient Type', dataType: 'IS', required: false, description: 'Patient type' },
      { position: 19, name: 'Visit Number', dataType: 'CX', required: false, description: 'Visit number' },
      { position: 20, name: 'Financial Class', dataType: 'FC', required: false, table: '0064', description: 'Financial class' },
      { position: 21, name: 'Charge Price Indicator', dataType: 'ID', required: false, description: 'Charge price indicator' },
      { position: 22, name: 'Courtesy Code', dataType: 'ID', required: false, description: 'Courtesy code' },
      { position: 23, name: 'Credit Rating', dataType: 'ID', required: false, description: 'Credit rating' },
      { position: 24, name: 'Contract Code', dataType: 'IS', required: false, description: 'Contract code' },
      { position: 25, name: 'Contract Effective Date', dataType: 'DT', required: false, description: 'Contract effective date' },
      { position: 26, name: 'Contract Amount', dataType: 'NM', required: false, description: 'Contract amount' },
      { position: 27, name: 'Contract Period', dataType: 'NM', required: false, description: 'Contract period' },
      { position: 28, name: 'Interest Code', dataType: 'ID', required: false, description: 'Interest code' },
      { position: 29, name: 'Transfer to Bad Debt Code', dataType: 'ID', required: false, description: 'Transfer to bad debt code' },
      { position: 30, name: 'Transfer to Bad Debt Date', dataType: 'DT', required: false, description: 'Transfer to bad debt date' },
      { position: 31, name: 'Bad Debt Agency Code', dataType: 'IS', required: false, description: 'Bad debt agency code' },
      { position: 32, name: 'Bad Debt Transfer Amount', dataType: 'NM', required: false, description: 'Bad debt transfer amount' },
      { position: 33, name: 'Bad Debt Recovery Amount', dataType: 'NM', required: false, description: 'Bad debt recovery amount' },
      { position: 34, name: 'Delete Account Indicator', dataType: 'ID', required: false, description: 'Delete account indicator' },
      { position: 35, name: 'Delete Account Date', dataType: 'DT', required: false, description: 'Delete account date' },
      { position: 36, name: 'Discharge Disposition', dataType: 'IS', required: false, table: '0112', description: 'Discharge disposition' },
      { position: 37, name: 'Discharged to Location', dataType: 'DLD', required: false, description: 'Discharged to location' },
      { position: 38, name: 'Diet Type', dataType: 'CE', required: false, description: 'Diet type' },
      { position: 39, name: 'Servicing Facility', dataType: 'IS', required: false, description: 'Servicing facility' },
      { position: 40, name: 'Bed Status', dataType: 'IS', required: false, description: 'Bed status' },
      { position: 41, name: 'Account Status', dataType: 'IS', required: false, description: 'Account status' },
      { position: 42, name: 'Pending Location', dataType: 'PL', required: false, description: 'Pending location' },
      { position: 43, name: 'Prior Temporary Location', dataType: 'PL', required: false, description: 'Prior temporary location' },
      { position: 44, name: 'Admit Date/Time', dataType: 'TS', required: false, description: 'Admit date/time' },
      { position: 45, name: 'Discharge Date/Time', dataType: 'TS', required: false, description: 'Discharge date/time' },
      { position: 46, name: 'Current Patient Balance', dataType: 'NM', required: false, description: 'Current patient balance' },
      { position: 47, name: 'Total Charges', dataType: 'NM', required: false, description: 'Total charges' },
      { position: 48, name: 'Total Adjustments', dataType: 'NM', required: false, description: 'Total adjustments' },
      { position: 49, name: 'Total Payments', dataType: 'NM', required: false, description: 'Total payments' },
      { position: 50, name: 'Alternate Visit ID', dataType: 'CX', required: false, description: 'Alternate visit ID' },
      { position: 51, name: 'Visit Indicator', dataType: 'ID', required: false, description: 'Visit indicator' },
      { position: 52, name: 'Other Healthcare Provider', dataType: 'XCN', required: false, description: 'Other healthcare provider' },
    ],
  },
  OBR: {
    name: 'OBR',
    description: 'Observation Request',
    fields: [
      { position: 1, name: 'Set ID', dataType: 'SI', required: false, description: 'Sequence identifier' },
      { position: 2, name: 'Placer Order Number', dataType: 'EI', required: false, description: 'Placer order number' },
      { position: 3, name: 'Filler Order Number', dataType: 'EI', required: false, description: 'Filler order number' },
      { position: 4, name: 'Universal Service Identifier', dataType: 'CE', required: true, description: 'Universal service identifier' },
      { position: 5, name: 'Priority', dataType: 'ID', required: false, table: '0485', description: 'Priority of the request' },
      { position: 6, name: 'Requested Date/Time', dataType: 'TS', required: false, description: 'Requested date/time' },
      { position: 7, name: 'Observation Date/Time', dataType: 'TS', required: false, description: 'Observation date/time' },
      { position: 8, name: 'Observation End Date/Time', dataType: 'TS', required: false, description: 'Observation end date/time' },
      { position: 9, name: 'Collection Volume', dataType: 'CQ', required: false, description: 'Collection volume' },
      { position: 10, name: 'Collector Identifier', dataType: 'XCN', required: false, description: 'Collector identifier' },
      { position: 11, name: 'Specimen Action Code', dataType: 'ID', required: false, description: 'Specimen action code' },
      { position: 12, name: 'Danger Code', dataType: 'CE', required: false, description: 'Danger code' },
      { position: 13, name: 'Relevant Clinical Information', dataType: 'CE', required: false, description: 'Relevant clinical information' },
      { position: 14, name: 'Specimen Received Date/Time', dataType: 'TS', required: false, description: 'Specimen received date/time' },
      { position: 15, name: 'Specimen Source', dataType: 'SPS', required: false, description: 'Specimen source' },
      { position: 16, name: 'Ordering Provider', dataType: 'XCN', required: false, description: 'Ordering provider' },
      { position: 17, name: 'Order Callback Phone Number', dataType: 'XTN', required: false, description: 'Order callback phone number' },
      { position: 18, name: 'Placer Field 1', dataType: 'ST', required: false, description: 'Placer field 1' },
      { position: 19, name: 'Placer Field 2', dataType: 'ST', required: false, description: 'Placer field 2' },
      { position: 20, name: 'Filler Field 1', dataType: 'ST', required: false, description: 'Filler field 1' },
      { position: 21, name: 'Filler Field 2', dataType: 'ST', required: false, description: 'Filler field 2' },
      { position: 22, name: 'Results Rpt/Status Chng - Date/Time', dataType: 'TS', required: false, description: 'Results report date/time' },
      { position: 23, name: 'Charge to Practice', dataType: 'MOP', required: false, description: 'Charge to practice' },
      { position: 24, name: 'Diagnostic Service Section ID', dataType: 'ID', required: false, table: '0074', description: 'Diagnostic service section ID' },
      { position: 25, name: 'Result Status', dataType: 'ID', required: false, table: '0123', description: 'Result status' },
      { position: 26, name: 'Parent Result', dataType: 'PRL', required: false, description: 'Parent result' },
      { position: 27, name: 'Quantity/Timing', dataType: 'TQ', required: false, description: 'Quantity/timing' },
      { position: 28, name: 'Result Copies To', dataType: 'XCN', required: false, description: 'Result copies to' },
      { position: 29, name: 'Parent', dataType: 'EIP', required: false, description: 'Parent' },
      { position: 30, name: 'Transportation Mode', dataType: 'ID', required: false, table: '0124', description: 'Transportation mode' },
      { position: 31, name: 'Reason for Study', dataType: 'CE', required: false, description: 'Reason for study' },
      { position: 32, name: 'Principal Result Interpreter', dataType: 'NDL', required: false, description: 'Principal result interpreter' },
      { position: 33, name: 'Assistant Result Interpreter', dataType: 'NDL', required: false, description: 'Assistant result interpreter' },
      { position: 34, name: 'Technician', dataType: 'NDL', required: false, description: 'Technician' },
      { position: 35, name: 'Transcriptionist', dataType: 'NDL', required: false, description: 'Transcriptionist' },
      { position: 36, name: 'Scheduled Date/Time', dataType: 'TS', required: false, description: 'Scheduled date/time' },
      { position: 37, name: 'Number of Sample Containers', dataType: 'NM', required: false, description: 'Number of sample containers' },
      { position: 38, name: 'Transport Logistics of Sample', dataType: 'CE', required: false, description: 'Transport logistics of sample' },
      { position: 39, name: 'Collector\'s Comment', dataType: 'CE', required: false, description: "Collector's comment" },
      { position: 40, name: 'Transport Arrangement Responsibility', dataType: 'CE', required: false, description: 'Transport arrangement responsibility' },
      { position: 41, name: 'Transport Arranged', dataType: 'ID', required: false, description: 'Transport arranged' },
      { position: 42, name: 'Transport Arranged', dataType: 'ID', required: false, description: 'Transport arranged need' },
      { position: 43, name: 'Specimen Type', dataType: 'CE', required: false, description: 'Specimen type' },
      { position: 44, name: 'Specimen Collection Date/Time', dataType: 'TS', required: false, description: 'Specimen collection date/time' },
      { position: 45, name: 'Specimen Type Modifier', dataType: 'CE', required: false, description: 'Specimen type modifier' },
      { position: 46, name: 'Specimen Source Site Modifier', dataType: 'CE', required: false, description: 'Specimen source site modifier' },
      { position: 47, name: 'Number of Specimen Sets', dataType: 'NM', required: false, description: 'Number of specimen sets' },
      { position: 48, name: 'Transport Logistics Specimen Type', dataType: 'CE', required: false, description: 'Transport logistics specimen type' },
    ],
  },
  OBX: {
    name: 'OBX',
    description: 'Observation/Result',
    fields: [
      { position: 1, name: 'Set ID', dataType: 'SI', required: false, description: 'Sequence identifier' },
      { position: 2, name: 'Value Type', dataType: 'ID', required: true, table: '0125', description: 'Value type (ST=String, NM=Numeric, CE=Coded Entry)' },
      { position: 3, name: 'Observation Identifier', dataType: 'CE', required: true, description: 'Observation identifier' },
      { position: 4, name: 'Observation Sub-ID', dataType: 'ST', required: false, description: 'Observation sub-ID' },
      { position: 5, name: 'Observation Value', dataType: 'ST', required: false, description: 'Observation value' },
      { position: 6, name: 'Units', dataType: 'CE', required: false, description: 'Units' },
      { position: 7, name: 'Reference Range', dataType: 'ST', required: false, description: 'Reference range' },
      { position: 8, name: 'Abnormal Flags', dataType: 'IS', required: false, table: '0078', description: 'Abnormal flags' },
      { position: 9, name: 'Probability', dataType: 'NM', required: false, description: 'Probability' },
      { position: 10, name: 'Nature of Abnormal Test', dataType: 'ID', required: false, description: 'Nature of abnormal test' },
      { position: 11, name: 'Observation Result Status', dataType: 'ID', required: false, table: '0085', description: 'Observation result status' },
      { position: 12, name: 'Date of Last Observation Normal Values', dataType: 'TS', required: false, description: 'Date of last observation normal values' },
      { position: 13, name: 'User Defined Access Checks', dataType: 'ST', required: false, description: 'User defined access checks' },
      { position: 14, name: 'Date/Time of the Observation', dataType: 'TS', required: false, description: 'Date/time of the observation' },
      { position: 15, name: 'Producer\'s ID', dataType: 'CE', required: false, description: "Producer's ID" },
      { position: 16, name: 'Responsible Observer', dataType: 'XCN', required: false, description: 'Responsible observer' },
      { position: 17, name: 'Observation Method', dataType: 'CE', required: false, description: 'Observation method' },
      { position: 18, name: 'Equipment Instance Identifier', dataType: 'EI', required: false, description: 'Equipment instance identifier' },
      { position: 19, name: 'Date/Time of the Analysis', dataType: 'TS', required: false, description: 'Date/time of the analysis' },
    ],
  },
  NK1: {
    name: 'NK1',
    description: 'Next of Kin',
    fields: [
      { position: 1, name: 'Set ID', dataType: 'SI', required: false, description: 'Sequence identifier' },
      { position: 2, name: 'Name', dataType: 'XPN', required: false, description: 'Next of kin name' },
      { position: 3, name: 'Relationship', dataType: 'CE', required: false, table: '0063', description: 'Relationship to patient' },
      { position: 4, name: 'Address', dataType: 'XAD', required: false, description: 'Next of kin address' },
      { position: 5, name: 'Phone Number', dataType: 'XTN', required: false, description: 'Next of kin phone number' },
      { position: 6, name: 'Business Phone Number', dataType: 'XTN', required: false, description: 'Next of kin business phone' },
      { position: 7, name: 'Contact Role', dataType: 'CE', required: false, table: '0131', description: 'Contact role' },
      { position: 8, name: 'Start Date', dataType: 'DT', required: false, description: 'Start date' },
      { position: 9, name: 'End Date', dataType: 'DT', required: false, description: 'End date' },
      { position: 10, name: 'Next of Kin / Associated Party Job Title', dataType: 'ST', required: false, description: 'Job title' },
      { position: 11, name: 'Next of Kin Job Code/Class', dataType: 'JCC', required: false, description: 'Job code/class' },
      { position: 12, name: 'Next of Kin Employee Number', dataType: 'CX', required: false, description: 'Employee number' },
      { position: 13, name: 'Organization Name', dataType: 'XON', required: false, description: 'Organization name' },
      { position: 14, name: 'Marital Status', dataType: 'CE', required: false, table: '0002', description: 'Marital status' },
      { position: 15, name: 'Administrative Sex', dataType: 'ID', required: false, table: '0001', description: 'Administrative sex' },
      { position: 16, name: 'Date/Time of Birth', dataType: 'TS', required: false, description: 'Date of birth' },
      { position: 17, name: 'Living Indicator', dataType: 'ID', required: false, description: 'Living indicator' },
      { position: 18, name: 'Ethnic Group', dataType: 'CE', required: false, table: '0189', description: 'Ethnic group' },
    ],
  },
  IN1: {
    name: 'IN1',
    description: 'Insurance',
    fields: [
      { position: 1, name: 'Set ID', dataType: 'SI', required: false, description: 'Sequence identifier' },
      { position: 2, name: 'Insurance Plan ID', dataType: 'CE', required: false, description: 'Insurance plan ID' },
      { position: 3, name: 'Insurance Company ID', dataType: 'CX', required: false, description: 'Insurance company ID' },
      { position: 4, name: 'Insurance Company Name', dataType: 'XON', required: false, description: 'Insurance company name' },
      { position: 5, name: 'Insurance Company Address', dataType: 'XAD', required: false, description: 'Insurance company address' },
      { position: 6, name: 'Insurance Company Contact Person', dataType: 'XPN', required: false, description: 'Contact person' },
      { position: 7, name: 'Insurance Company Phone Number', dataType: 'XTN', required: false, description: 'Phone number' },
      { position: 8, name: 'Group Number', dataType: 'ST', required: false, description: 'Group number' },
      { position: 9, name: 'Group Name', dataType: 'ST', required: false, description: 'Group name' },
      { position: 10, name: 'Insured\'s Group Employer ID', dataType: 'CX', required: false, description: "Insured's group employer ID" },
      { position: 11, name: 'Insured\'s Group Employer Name', dataType: 'XON', required: false, description: "Insured's group employer name" },
      { position: 12, name: 'Plan Effective Date', dataType: 'DT', required: false, description: 'Plan effective date' },
      { position: 13, name: 'Plan Expiration Date', dataType: 'DT', required: false, description: 'Plan expiration date' },
      { position: 14, name: 'Authorization Information', dataType: 'AUI', required: false, description: 'Authorization information' },
      { position: 15, name: 'Plan Type', dataType: 'ID', required: false, table: '0144', description: 'Plan type' },
      { position: 16, name: 'Name of Insured', dataType: 'XPN', required: false, description: 'Name of insured' },
      { position: 17, name: 'Insured\'s Relationship to Patient', dataType: 'ID', required: false, table: '0063', description: "Insured's relationship to patient" },
      { position: 18, name: 'Insured\'s Date of Birth', dataType: 'TS', required: false, description: "Insured's date of birth" },
      { position: 19, name: 'Insured\'s Address', dataType: 'XAD', required: false, description: "Insured's address" },
      { position: 20, name: 'Assignment of Benefits', dataType: 'ID', required: false, description: 'Assignment of benefits' },
      { position: 21, name: 'Coordination of Benefits', dataType: 'ID', required: false, description: 'Coordination of benefits' },
      { position: 22, name: 'Coordination of Benefits - Priority', dataType: 'ST', required: false, description: 'Coordination of benefits priority' },
      { position: 23, name: 'Notice of Admission Flag', dataType: 'ID', required: false, description: 'Notice of admission flag' },
      { position: 24, name: 'Notice of Admission Date', dataType: 'DT', required: false, description: 'Notice of admission date' },
      { position: 25, name: 'Report of Eligibility Flag', dataType: 'ID', required: false, description: 'Report of eligibility flag' },
      { position: 26, name: 'Report of Eligibility Date', dataType: 'DT', required: false, description: 'Report of eligibility date' },
      { position: 27, name: 'Release Information Code', dataType: 'ID', required: false, description: 'Release information code' },
      { position: 28, name: 'Pre-Admit Certification', dataType: 'ST', required: false, description: 'Pre-admit certification' },
      { position: 29, name: 'Verification of Date/Time', dataType: 'TS', required: false, description: 'Verification date/time' },
      { position: 30, name: 'Verification of By', dataType: 'XPN', required: false, description: 'Verification by' },
      { position: 31, name: 'Type of Agreement Code', dataType: 'ID', required: false, description: 'Type of agreement code' },
      { position: 32, name: 'Billing Status', dataType: 'ID', required: false, description: 'Billing status' },
      { position: 33, name: 'Lifetime Reserve Days', dataType: 'NM', required: false, description: 'Lifetime reserve days' },
      { position: 34, name: 'Delay Before L.R. Day', dataType: 'NM', required: false, description: 'Delay before L.R. day' },
      { position: 35, name: 'Company Plan Code', dataType: 'IS', required: false, description: 'Company plan code' },
      { position: 36, name: 'Policy Number', dataType: 'ST', required: false, description: 'Policy number' },
      { position: 37, name: 'Policy Deductible', dataType: 'NM', required: false, description: 'Policy deductible' },
      { position: 38, name: 'Policy Limit - Amount', dataType: 'NM', required: false, description: 'Policy limit amount' },
      { position: 39, name: 'Policy Limit - Days', dataType: 'NM', required: false, description: 'Policy limit days' },
      { position: 40, name: 'Room Rate - Semi-Private', dataType: 'NM', required: false, description: 'Room rate semi-private' },
      { position: 41, name: 'Room Rate - Private', dataType: 'NM', required: false, description: 'Room rate private' },
      { position: 42, name: 'Insured\'s Employment Status', dataType: 'CE', required: false, description: "Insured's employment status" },
      { position: 43, name: 'Insured\'s Administrative Sex', dataType: 'ID', required: false, table: '0001', description: "Insured's administrative sex" },
      { position: 44, name: 'Insured\'s Employer Address', dataType: 'XAD', required: false, description: "Insured's employer address" },
      { position: 45, name: 'Verification Status', dataType: 'ST', required: false, description: 'Verification status' },
      { position: 46, name: 'Prior Insurance Plan ID', dataType: 'CE', required: false, description: 'Prior insurance plan ID' },
      { position: 47, name: 'Coverage Type', dataType: 'IS', required: false, description: 'Coverage type' },
      { position: 48, name: 'Handicap', dataType: 'IS', required: false, description: 'Handicap' },
      { position: 49, name: 'Insured\'s Phone Number', dataType: 'XTN', required: false, description: "Insured's phone number" },
      { position: 50, name: 'Insured\'s Telephone Number - Business', dataType: 'XTN', required: false, description: "Insured's business phone" },
      { position: 51, name: 'Coordination of Benefits - Percent', dataType: 'NM', required: false, description: 'Coordination of benefits percent' },
    ],
  },
  AL1: {
    name: 'AL1',
    description: 'Patient Allergy Information',
    fields: [
      { position: 1, name: 'Set ID', dataType: 'SI', required: false, description: 'Sequence identifier' },
      { position: 2, name: 'Allergen Type Code', dataType: 'CE', required: false, table: '0127', description: 'Allergen type code' },
      { position: 3, name: 'Allergen Code/Mnemonic/Description', dataType: 'CE', required: false, description: 'Allergen code or description' },
      { position: 4, name: 'Allergy Severity Code', dataType: 'CE', required: false, table: '0128', description: 'Allergy severity code' },
      { position: 5, name: 'Allergy Reaction Code', dataType: 'ST', required: false, description: 'Allergy reaction code' },
      { position: 6, name: 'Identification Date', dataType: 'DT', required: false, description: 'Identification date' },
    ],
  },
  DG1: {
    name: 'DG1',
    description: 'Diagnosis',
    fields: [
      { position: 1, name: 'Set ID', dataType: 'SI', required: false, description: 'Sequence identifier' },
      { position: 2, name: 'Diagnosis Coding Method', dataType: 'ID', required: true, table: '0053', description: 'Diagnosis coding method (ICD9, ICD10)' },
      { position: 3, name: 'Diagnosis Code', dataType: 'CE', required: false, description: 'Diagnosis code' },
      { position: 4, name: 'Diagnosis Description', dataType: 'ST', required: false, description: 'Diagnosis description' },
      { position: 5, name: 'Diagnosis Date/Time', dataType: 'TS', required: false, description: 'Diagnosis date/time' },
      { position: 6, name: 'Diagnosis Type', dataType: 'IS', required: false, table: '0107', description: 'Diagnosis type' },
      { position: 7, name: 'Major Diagnostic Category', dataType: 'CE', required: false, description: 'Major diagnostic category' },
      { position: 8, name: 'Diagnostic Related Group', dataType: 'CE', required: false, description: 'Diagnostic related group' },
      { position: 9, name: 'DRG Approval Indicator', dataType: 'ID', required: false, description: 'DRG approval indicator' },
      { position: 10, name: 'DRG Grouper Review Code', dataType: 'ID', required: false, description: 'DRG grouper review code' },
      { position: 11, name: 'Outlier Type', dataType: 'ID', required: false, description: 'Outlier type' },
      { position: 12, name: 'Outlier Days', dataType: 'NM', required: false, description: 'Outlier days' },
      { position: 13, name: 'Outlier Cost', dataType: 'NM', required: false, description: 'Outlier cost' },
      { position: 14, name: 'Grouper Version And Type', dataType: 'ST', required: false, description: 'Grouper version and type' },
      { position: 15, name: 'Diagnosis Priority', dataType: 'ID', required: false, description: 'Diagnosis priority' },
      { position: 16, name: 'Diagnosing Clinician', dataType: 'XCN', required: false, description: 'Diagnosing clinician' },
    ],
  },
  ORC: {
    name: 'ORC',
    description: 'Common Order',
    fields: [
      { position: 1, name: 'Order Control', dataType: 'ID', required: true, table: '0119', description: 'Order control code (NW=New, SC=Status Change)' },
      { position: 2, name: 'Placer Order Number', dataType: 'EI', required: false, description: 'Placer order number' },
      { position: 3, name: 'Filler Order Number', dataType: 'EI', required: false, description: 'Filler order number' },
      { position: 4, name: 'Placer Group Number', dataType: 'EI', required: false, description: 'Placer group number' },
      { position: 5, name: 'Order Status', dataType: 'ID', required: false, table: '0038', description: 'Order status' },
      { position: 6, name: 'Response Flag', dataType: 'ID', required: false, table: '0121', description: 'Response flag' },
      { position: 7, name: 'Quantity/Timing', dataType: 'TQ', required: false, description: 'Quantity/timing' },
      { position: 8, name: 'Parent Order', dataType: 'EIP', required: false, description: 'Parent order' },
      { position: 9, name: 'Date/Time of Transaction', dataType: 'TS', required: false, description: 'Date/time of transaction' },
      { position: 10, name: 'Entered By', dataType: 'XCN', required: false, description: 'Entered by' },
      { position: 11, name: 'Verified By', dataType: 'XCN', required: false, description: 'Verified by' },
      { position: 12, name: 'Ordering Provider', dataType: 'XCN', required: false, description: 'Ordering provider' },
      { position: 13, name: 'Enterer\'s Location', dataType: 'PL', required: false, description: "Enterer's location" },
      { position: 14, name: 'Call Back Phone Number', dataType: 'XTN', required: false, description: 'Call back phone number' },
      { position: 15, name: 'Order Effective Date/Time', dataType: 'TS', required: false, description: 'Order effective date/time' },
    ],
  },
};

export function getFieldDef(segmentId: string, position: number): FieldDef | undefined {
  const seg = SEGMENT_DEFS[segmentId];
  if (!seg) return undefined;
  return seg.fields.find((f) => f.position === position);
}

export function getSegmentDef(segmentId: string): SegmentDef | undefined {
  return SEGMENT_DEFS[segmentId];
}
