export interface TableEntry {
  value: string;
  description: string;
}

export const HL7_TABLES: Record<string, TableEntry[]> = {
  '0001': [
    { value: 'A', description: 'Ambiguous' },
    { value: 'F', description: 'Female' },
    { value: 'M', description: 'Male' },
    { value: 'N', description: 'Not Reported' },
    { value: 'O', description: 'Other' },
    { value: 'U', description: 'Unknown' },
  ],
  '0002': [
    { value: 'A', description: 'Separated' },
    { value: 'D', description: 'Divorced' },
    { value: 'M', description: 'Married' },
    { value: 'S', description: 'Single' },
    { value: 'W', description: 'Widowed' },
    { value: 'C', description: 'Common Law' },
    { value: 'P', description: 'Domestic Partner' },
    { value: 'T', description: 'Unreported' },
    { value: 'U', description: 'Unknown' },
  ],
  '0004': [
    { value: 'B', description: 'Obstetrics' },
    { value: 'C', description: 'Commercial Account' },
    { value: 'E', description: 'Emergency' },
    { value: 'I', description: 'Inpatient' },
    { value: 'N', description: 'Not Applicable' },
    { value: 'O', description: 'Outpatient' },
    { value: 'P', description: 'Preadmit' },
    { value: 'R', description: 'Recurring patient' },
    { value: 'U', description: 'Unknown' },
  ],
  '0005': [
    { value: 'AIAN', description: 'American Indian or Alaska Native' },
    { value: 'ASIAN', description: 'Asian' },
    { value: 'BLACK', description: 'Black or African American' },
    { value: 'HISP', description: 'Hispanic or Latino' },
    { value: 'NHPI', description: 'Native Hawaiian or Other Pacific Islander' },
    { value: 'WHITE', description: 'White' },
    { value: 'OTH', description: 'Other' },
    { value: 'UNK', description: 'Unknown' },
  ],
  '0006': [
    { value: 'AGN', description: 'Agnostic' },
    { value: 'ATH', description: 'Atheist' },
    { value: 'BAH', description: 'BahaI' },
    { value: 'BRE', description: 'Brethren' },
    { value: 'BUD', description: 'Buddhism' },
    { value: 'CAT', description: 'Roman Catholic' },
    { value: 'CHR', description: 'Christian' },
    { value: 'HIN', description: 'Hindu' },
    { value: 'JEW', description: 'Jewish' },
    { value: 'MOR', description: 'Mormon' },
    { value: 'MOS', description: 'Muslim' },
    { value: 'NON', description: 'Non-denominational' },
    { value: 'OTH', description: 'Other' },
    { value: 'PRO', description: 'Protestant' },
  ],
  '0007': [
    { value: 'A', description: 'Accident' },
    { value: 'E', description: 'Emergency' },
    { value: 'L', description: 'Labor and Delivery' },
    { value: 'R', description: 'Routine' },
    { value: 'N', description: 'Newborn (Birth in facility)' },
    { value: 'U', description: 'Urgent' },
    { value: 'C', description: 'Elective' },
  ],
  '0008': [
    { value: 'A', description: 'Separated' },
    { value: 'D', description: 'Divorced' },
    { value: 'M', description: 'Married' },
    { value: 'S', description: 'Single' },
    { value: 'W', description: 'Widowed' },
    { value: 'C', description: 'Common Law' },
    { value: 'P', description: 'Domestic Partner' },
    { value: 'T', description: 'Unreported' },
    { value: 'U', description: 'Unknown' },
  ],
  '0023': [
    { value: 'LD', description: 'Left Against Advice' },
    { value: 'RL', description: 'Left - Returned Later' },
    { value: 'TR', description: 'Transferred to Another Facility' },
    { value: 'DI', description: 'Died' },
    { value: 'EX', description: 'Expired' },
    { value: 'CO', description: 'Court/Law Enforcement' },
  ],
  '0038': [
    { value: 'CA', description: 'Cancelled' },
    { value: 'DC', description: 'Discontinued' },
    { value: 'ER', description: 'Error' },
    { value: 'HD', description: 'On Hold' },
    { value: 'IP', description: 'In Process' },
    { value: 'NA', description: 'Not Admitted/Not Arrived' },
    { value: 'OR', description: 'Not Started' },
    { value: 'PA', description: 'Parent Order' },
    { value: 'RP', description: 'Replaced' },
    { value: 'RQ', description: 'Requested' },
    { value: 'SC', description: 'Scheduled' },
    { value: 'CM', description: 'Completed' },
  ],
  '0053': [
    { value: 'I9', description: 'ICD-9-CM' },
    { value: 'I10', description: 'ICD-10-CM' },
    { value: 'SNM', description: 'Systematized Nomenclature of Medicine' },
    { value: 'OTH', description: 'Other' },
  ],
  '0063': [
    { value: 'ASC', description: 'Associate' },
    { value: 'BRO', description: 'Brother' },
    { value: 'CGV', description: 'Care giver' },
    { value: 'CHD', description: 'Child' },
    { value: 'EME', description: 'Employee' },
    { value: 'EMR', description: 'Employer' },
    { value: 'EXF', description: 'Extended family' },
    { value: 'FCH', description: 'Foster child' },
    { value: 'FND', description: 'Funding source' },
    { value: 'FTH', description: 'Father' },
    { value: 'GCH', description: 'Grandchild' },
    { value: 'GRD', description: 'Guardian' },
    { value: 'GRP', description: 'Grandparent' },
    { value: 'MTH', description: 'Mother' },
    { value: 'NOK', description: 'Next of kin' },
    { value: 'OTH', description: 'Other' },
    { value: 'SIS', description: 'Sister' },
    { value: 'SPO', description: 'Spouse' },
    { value: 'UNE', description: 'Unemployed' },
    { value: 'UNK', description: 'Unknown' },
  ],
  '0064': [
    { value: '01', description: 'Private' },
    { value: '02', description: 'Public' },
    { value: '03', description: 'Workers Compensation' },
    { value: '04', description: 'Medicare' },
    { value: '05', description: 'Medicaid' },
    { value: '06', description: 'No Fault' },
    { value: '07', description: 'Self Pay' },
    { value: '08', description: 'Other' },
  ],
  '0074': [
    { value: 'AU', description: 'Audiology' },
    { value: 'BG', description: 'Blood Bank' },
    { value: 'BL', description: 'Cardiac Catheterization' },
    { value: 'CG', description: 'Cytogenetics' },
    { value: 'CH', description: 'Chemistry' },
    { value: 'CP', description: 'Cytopathology' },
    { value: 'CT', description: 'Cat Scan' },
    { value: 'HM', description: 'Hematology' },
    { value: 'IC', description: 'Immunology' },
    { value: 'MB', description: 'Microbiology' },
    { value: 'MC', description: 'MedChem' },
    { value: 'MR', description: 'MRI' },
    { value: 'MY', description: 'Mycology' },
    { value: 'NM', description: 'Nuclear Medicine' },
    { value: 'OS', description: 'Osteoporosis' },
    { value: 'OT', description: 'Other' },
    { value: 'PA', description: 'Pathology ( gross & histology)' },
    { value: 'PH', description: 'Histopathology' },
    { value: 'PP', description: 'Pap Smears' },
    { value: 'PX', description: 'Probe X-Ray' },
    { value: 'RB', description: 'Red Blood Cells' },
    { value: 'RC', description: 'Radiology' },
    { value: 'RN', description: 'RN Only' },
    { value: 'RT', description: 'Radiation Therapy' },
    { value: 'RX', description: 'Radiology X-Ray' },
    { value: 'SP', description: 'Surgical Pathology' },
    { value: 'SR', description: 'Serology' },
    { value: 'TM', description: 'Toxicology' },
    { value: 'UR', description: 'Urinalysis' },
    { value: 'VI', description: 'Virology' },
    { value: 'WL', description: 'Whole Blood' },
  ],
  '0078': [
    { value: 'A', description: 'Critical abnormal' },
    { value: 'H', description: 'Above high normal' },
    { value: 'L', description: 'Below low normal' },
    { value: 'N', description: 'Normal' },
    { value: 'A>', description: 'Very abnormal' },
    { value: 'N', description: 'Normal' },
    { value: 'AA', description: 'Very critical abnormal' },
    { value: 'HH', description: 'Above upper panic limits' },
    { value: 'LL', description: 'Below lower panic limits' },
  ],
  '0085': [
    { value: 'C', description: 'Corrected, not final' },
    { value: 'F', description: 'Final results' },
    { value: 'I', description: 'Preliminary results' },
    { value: 'P', description: 'Preliminary results' },
    { value: 'R', description: 'Results entered -- not verified' },
    { value: 'S', description: 'Partial results' },
    { value: 'X', description: 'No results available; Order canceled' },
  ],
  '0107': [
    { value: 'A', description: 'Admitting' },
    { value: 'W', description: 'Working' },
    { value: 'F', description: 'Final' },
    { value: 'O', description: 'Other' },
  ],
  '0112': [
    { value: '01', description: 'Discharged to home or self care' },
    { value: '02', description: 'Discharged/transferred to short-term general hospital' },
    { value: '03', description: 'Discharged/transferred to SNF' },
    { value: '04', description: 'Discharged/transferred to ICF' },
    { value: '05', description: 'Discharged/transferred to another type of institution' },
    { value: '06', description: 'Discharged/transferred to home under care of organized home health service' },
    { value: '07', description: 'Left against medical advice' },
    { value: '08', description: 'Discharged/transferred to home under care of home IV provider' },
    { value: '09', description: 'Admitted as inpatient to this hospital' },
    { value: '20', description: 'Expired in facility' },
    { value: '50', description: 'Hospice - home' },
    { value: '51', description: 'Hospice - medical facility' },
    { value: '61', description: 'Discharged/transferred within institution to Medicare-approved swing bed' },
    { value: '62', description: 'Discharged/transferred to inpatient rehab facility' },
    { value: '63', description: 'Discharged/transferred to long-term care hospital' },
    { value: '64', description: 'Discharged/transferred to nursing facility certified under Medicaid' },
    { value: '65', description: 'Discharged/transferred to a cancer center' },
    { value: '66', description: 'Discharged/transferred to a psychiatric hospital' },
    { value: '99', description: 'Not specified' },
  ],
  '0119': [
    { value: 'NW', description: 'New Order' },
    { value: 'OK', description: 'Order Accepted & OK' },
    { value: 'SC', description: 'Status Change' },
    { value: 'CA', description: 'Cancel Order' },
    { value: 'DC', description: 'Discontinue Order' },
    { value: 'HD', description: 'Hold Order' },
    { value: 'OC', description: 'Cancel Order' },
    { value: 'OR', description: 'Released as Entered' },
    { value: 'RE', description: 'Observations/Performed Service to Follow' },
    { value: 'RF', description: 'Refuse Order' },
    { value: 'RO', description: 'Replace Order' },
    { value: 'RQ', description: 'Replace Order Request' },
    { value: 'XR', description: 'Changed Order' },
  ],
  '0121': [
    { value: 'A', description: 'Apply: Receiver is not authorized to apply' },
    { value: 'R', description: 'Refuse: Receiver must refuse' },
    { value: 'E', description: 'Exception: Receiver may process' },
    { value: 'N', description: 'Notification Only' },
  ],
  '0123': [
    { value: 'O', description: 'Order Received' },
    { value: 'R', description: 'Results Pending' },
    { value: 'S', description: 'Partial Results' },
    { value: 'C', description: 'Corrected Results' },
    { value: 'F', description: 'Final Results' },
    { value: 'X', description: 'No Results' },
  ],
  '0124': [
    { value: 'CUR', description: 'Courier' },
    { value: 'GROUND', description: 'Ground' },
    { value: 'AIR', description: 'Air' },
    { value: 'WALK', description: 'Walk In' },
  ],
  '0125': [
    { value: 'ST', description: 'String data' },
    { value: 'NM', description: 'Numeric' },
    { value: 'SN', description: 'Structured Numeric' },
    { value: 'DT', description: 'Date' },
    { value: 'TM', description: 'Time' },
    { value: 'TS', description: 'Time Stamp' },
    { value: 'CE', description: 'Coded Entry' },
    { value: 'CF', description: 'Coded Element with Formatted Values' },
    { value: 'TX', description: 'Text Data' },
    { value: 'FT', description: 'Formatted Text' },
    { value: 'ID', description: 'Coded Value Identifier' },
    { value: 'IS', description: 'Coded Value Identifier' },
    { value: 'ED', description: 'Encapsulated Data' },
    { value: 'AD', description: 'Address' },
    { value: 'PN', description: 'Person Name' },
    { value: 'XPN', description: 'Extended Person Name' },
    { value: 'XAD', description: 'Extended Address' },
    { value: 'XCN', description: 'Extended Composite ID Number and Name' },
  ],
  '0127': [
    { value: 'DA', description: 'Drug' },
    { value: 'FA', description: 'Food' },
    { value: 'MA', description: 'Animal' },
    { value: 'MC', description: 'Miscellaneous' },
    { value: 'PL', description: 'Plant' },
    { value: 'AA', description: 'Other' },
  ],
  '0128': [
    { value: 'SV', description: 'Severe' },
    { value: 'MO', description: 'Moderate' },
    { value: 'MI', description: 'Mild' },
    { value: 'U', description: 'Unknown' },
  ],
  '0131': [
    { value: 'E', description: 'Employer' },
    { value: 'C', description: 'Emergency Contact' },
    { value: 'F', description: 'Federal Agency' },
    { value: 'O', description: 'Other' },
    { value: 'PR', description: 'Primary Care Provider' },
    { value: 'I', description: 'Insurance Company' },
    { value: 'N', description: 'Next of Kin' },
    { value: 'S', description: 'State Agency' },
    { value: 'U', description: 'Unknown' },
  ],
  '0144': [
    { value: 'HM', description: 'Home Health Plan' },
    { value: 'HM', description: 'Home' },
    { value: 'DG', description: 'Disability' },
    { value: 'DC', description: 'Dental Care' },
    { value: 'WC', description: 'Workers Compensation' },
    { value: 'SS', description: 'Social Security' },
    { value: 'PL', description: 'Personal' },
    { value: 'MM', description: 'Medicare' },
    { value: 'MD', description: 'Medicaid' },
    { value: 'MP', description: 'Medicare Part A' },
    { value: 'MB', description: 'Medicare Part B' },
    { value: 'GP', description: 'Group Plan' },
    { value: 'PR', description: 'Private Health Insurance' },
    { value: 'OF', description: 'Other Federal Program' },
    { value: 'BC', description: 'Blue Cross/Blue Shield' },
    { value: 'VA', description: 'Veterans Affairs Plan' },
    { value: 'SP', description: 'Sponsored Plan' },
    { value: 'HM', description: 'HMO' },
    { value: 'PPO', description: 'PPO' },
    { value: 'POS', description: 'POS' },
  ],
  '0155': [
    { value: 'AL', description: 'Always' },
    { value: 'NE', description: 'Never' },
    { value: 'ER', description: 'Error/Reject Conditions' },
    { value: 'SU', description: 'Successful Completion Only' },
  ],
  '0189': [
    { value: 'H', description: 'Hispanic or Latino' },
    { value: 'N', description: 'Not Hispanic or Latino' },
    { value: 'U', description: 'Unknown' },
  ],
  '0485': [
    { value: 'S', description: 'Stat' },
    { value: 'R', description: 'Routine' },
    { value: 'A', description: 'ASAP' },
    { value: 'P', description: 'Preop' },
    { value: 'C', description: 'Callback' },
  ],
};

export function lookupTable(tableId: string): TableEntry[] | undefined {
  return HL7_TABLES[tableId];
}

export function lookupValue(tableId: string, code: string): string | undefined {
  const table = HL7_TABLES[tableId];
  if (!table) return undefined;
  const entry = table.find((e) => e.value === code);
  return entry?.description;
}
